name: Clojure CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: lein deps
    - name: Build uberjar
      run: lein uberjar
    - name: Upload uberjar
      uses: actions/upload-artifact@v3
      with:
        name: clockify-cli-standalone.jar
        path: target/uberjar/clockify-cli-standalone.jar
