name: Clojure CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: lein deps
    - name: Build uberjar
      run: lein uberjar
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: /home/runner/work/clockify-cli/clockify-cli/target/uberjar/clockify-cli-standalone.jar
  
